Add Xresources-based theme
darrenburns/posting pull request #35
Opened 2024-07-12 13:49 UTC by SqrtMinusOne

I use Xresources to configure themes. This PR adds themes called `xresources-light` and `xresources-dark`, provided that `xrdb` is found and `xrdb -query` returns the necessary colors.

This is a bit suboptimal for light theme (which I use), because light themes don't need as much shading as C-o and C-p currently do. But `solarized-light` also has this issue.

2024-07-14 15:44 UTC, darrenburns commented on src/posting/app.py
> +        self.try_to_add_xresources_theme()
I'd want to put this behind a config option `use_xresources` which is `False` by default. If that option is `True`, then this method would be called.

It should also be possible to set the theme to `xresources-dark` or `xresources-light` directly from the config file (e.g. `theme: xresource-dark`).

2024-07-14 15:44 UTC, darrenburns requested changes
I'd like this to sit behind a config option.

2024-07-14 15:45 UTC, darrenburns commented
Thanks for the contribution! - I've done a short review, let me know what you think or if you need help.

2024-07-16 15:29 UTC, SqrtMinusOne commented
Done. I've:
- add an option called `use_xresources`, as you suggested;
- changed the method to fail with more verbose errors in case something goes wrong;
- moved the invocation of the method from `on_mount` to the constructor. I'm not sure if there's a more suitable place for it, but it works.

2024-07-16 16:52 UTC, SqrtMinusOne commented
Oops, my Emacs has auto-formatted the table in the README. I hope you don't mind.

2024-07-17 08:12 UTC, darrenburns commented
Thanks! I'll try to review this this week.

2024-07-22 21:29 UTC, darrenburns commented
Thank you - I've made a few minor changes. Moved stuff into a new module to keep it separate from the `App`, an simplified the code a bit.

Would you mind giving it a quick test? If it looks good to you I will merge.

2024-07-24 22:25 UTC, merged

2024-07-25 22:03 UTC, SqrtMinusOne commented
Thanks.

The current version fails with:
```
  File "/home/pavel/00-Scratch/posting/src/posting/xresources.py", line 36, in load_xresources_themes
    missing_colors = set(XRDB_MAPPING.values()) - supplied_colors.keys()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
```

The point of `list(itertools.chain(*self.XRDB_MAPPING.values()))` vas to flatten that list. I'll make a new PR with a fix.